trigger:
- develop

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'

steps:

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: 'SimionZoo.sln'

- task: VSBuild@1
  displayName: 'Build all the Win32 projects'
  inputs:
    platform: x86
    configuration: release

- task: VSBuild@1
  displayName: 'Build all the Win64 projects'
  inputs:
    platform: x64
    configuration: release

- task: VSTest@2
  displayName: 'Run x86 tests'
  inputs:
    platform: x86
    configuration: release

- task: VSTest@2
  displayName: 'Run x64 tests'
  inputs:
    platform: x64
    configuration: release